[build]
  publish = "public"
  command = "hugo"

[build.environment]
  HUGO_VERSION = "0.148.2"
  HUGO_ENV = "production"
  HUGO_ENABLEGITINFO = "true"

[context.production.environment]
  HUGO_VERSION = "0.148.2"

[[redirects]]
  from = "/admin/*"
  to = "/admin/index.html"
  status = 200
