[build]
publish = "public"
command = "hugo"

[build.environment]
HUGO_VERSION = "0.148.2"
HUGO_ENABLEGITINFO = "true"

[[redirects]]
  from = "/admin/*"
  to = "/admin/index.html"
  status = 200

[[edge_functions]]
path = "/admin/*"
function = "admin-auth"

[[redirects]]
  from = "/login"
  to = "/login.html"
  status = 200
