[build]
  publish = "public"
  command = "hugo --minify"

[build.environment]
  HUGO_VERSION = "0.124.0"

[[redirects]]
  from = "/posts/*"
  to = "https://blog.onurcangenc.com.tr/posts/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
