backend:
  name: git-gateway
  branch: main

media_folder: "static/uploads"
public_folder: "/uploads"

collections:
  - name: "posts"
    label: "Posts"
    folder: "content/posts"
    create: true
    slug: "{{slug}}"
    fields:
      - { name: "title", label: "Title" }
      - { name: "description", label: "Description" }
      - { name: "date", label: "Date", widget: "datetime" }
      - { name: "thumbnail", label: "Thumbnail", widget: "image" }
      - { name: "tags", label: "Tags", widget: "list" }
      - { name: "body", label: "Body", widget: "markdown" }
